[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'

[[plugins]]
repo = 'neoclide/denite-git'
on_source = 'denite.nvim'
hook_source = '''
call dein#add('Shougo/denite.nvim')
call dein#add('chemzqm/vim-easygit')
call dein#add('chemzqm/denite-git')
call denite#custom#map(
      \ 'normal',
      \ 'a',
      \ '<denite:do_action:add>',
      \ 'noremap'
      \)

call denite#custom#map(
      \ 'normal',
      \ 'd',
      \ '<denite:do_action:delete>',
      \ 'noremap'
      \)

call denite#custom#map(
      \ 'normal',
      \ 'r',
      \ '<denite:do_action:reset>',
      \ 'noremap'
      \)
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = '''
if executable('rg')
  call denite#custom#var('file/rec', 'command',
        \ ['rg', '--files', '--glob', '!.git'])
  call denite#custom#var('grep', 'command', ['rg', '--threads', '1'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
  call denite#custom#var('grep', 'default_opts',
        \ ['--vimgrep', '--no-heading'])
else
  call denite#custom#var('file/rec', 'command',
        \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
endif

if has('nvim')
  call denite#custom#source('file/rec', 'matchers',
        \ ['matcher/cpsm'])
endif

call denite#custom#map('insert', "'",
    \ '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('normal', 'r',
    \ '<denite:do_action:quickfix>', 'noremap')
call denite#custom#map('insert', '<BS>',
    \ '<denite:smart_delete_char_before_caret>', 'noremap')
call denite#custom#map('insert', '<C-h>',
    \ '<denite:smart_delete_char_before_caret>', 'noremap')

call denite#custom#option('default', {
    \ 'auto_accel': v:true,
    \ 'prompt': '>',
    \ 'source_names': 'short',
    \ })

let s:menus = {}
let s:menus.vim = {
    \ 'description': 'Vim',
    \ }
let s:menus.vim.file_candidates = [
    \ ['    > Edit configuation file (init.vim)', '~/.config/nvim/init.vim']
    \ ['    > Edit configuation file (.zshrc)', '~/.zshrc']
    \ ['    > Edit project file (AGW)', '~/Desktop/agw-gateway']
    \ ['    > Edit project file (AGW-dashboard)', '~/Desktop/agw-gateway-dashboard']
    \ ]
call denite#custom#var('menu', 'menus', s:menus)

call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
    \ [ '.git/', '.ropeproject/', '__pycache__/', 'tags',
    \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/',
    \   'node_modules/', 'target/', '.nuxt/', 'dist/', '.serverless/',
    \   '.serverless_plugins'])

let ignore=&wildignore .
      \ ',*.pyc,.git,.hg,.svn,.serverless,__pycache__,.serverless_plugins,.nuxt,tags,node_modules,.git/tags'
call denite#custom#var('file/rec', 'command',
      \ ['scantree.py', '--ignore', ignore])

call denite#custom#map(
    \ 'normal',
    \ 'rp',
    \ '<denite:do_action:qfreplace>',
    \ 'noremap')

" https://qiita.com/hrsh7th@github/items/303d46ba13532c502828 {{{
if dein#tap('denite.nvim') && dein#tap('vim-qfreplace')
  function! DeniteQfreplace(context)
    let qflist = []
    for target in a:context['targets']
      if !has_key(target, 'action__path') | continue | endif
      if !has_key(target, 'action__line') | continue | endif
      if !has_key(target, 'action__text') | continue | endif

      call add(qflist, {
            \ 'filename': target['action__path'],
            \ 'lnum': target['action__line'],
            \ 'text': target['word'],
            \ })
    endfor
    call setqflist(qflist)
    call qfreplace#start('tabnew')
  endfunction
  call denite#custom#action('file', 'qfreplace', function('DeniteQfreplace'))
endif
" }}}
'''
hook_add = '''
nnoremap <silent> ;;
      \ :<C-u>Denite command command_history<CR>
'''

#--------------------
# deoplete
#--------------------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['nvim-yarp']
on_event = 'InsertEnter'
hook_source = '''
let g:deoplete#enable_at_startup = 1
call deoplete#initialize()
call deoplete#custom#source('_', 'converters', [
      \ 'converter_auto_paren',
      \ 'converter_remove_overlap',
      \ 'converter_truncate_abbr',
      \ 'converter_truncate_menu',
      \ ])
call deoplete#custom#source('look', 'rank', 0)
inoremap <silent> <expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ deoplete#manual_complete()
inoremap <silent> <expr> <S-TAB>
      \ pumvisible() ? "\<C-p>" :
      \ <SID>check_back_space() ? "\<S-TAB>" :
      \ deoplete#manual_complete()
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1] =~# '\s'
endfunction
'''
hook_post_update = '!pip3 install -U --user neovim'

[[plugins]]
repo = 'ujihisa/neco-look'
depends = 'deoplete.nvim'
if ='''has('nvim')'''
hook_source = '''
let g:neocomplete#text_mode_filetypes = { "_" : 1 }
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_source = '''
  let g:neosnippet#snippets_directory="~/.cache/dein/repos/github.com/Shougo/neosnippet-snippets/neosnippets/"
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
depends = ['deoplete.nvim', 'tern_for_vim']
on_ft = ['javascript']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft   = ['python']
depends = ['deoplete.nvim', 'jedi-vim']
hook_source = '''
  let g:deoplete#sources#jedi#enable_cache   = 1
  let g:deoplete#sources#jedi#show_docstring = 1
'''

[[plugins]]
repo = 'padawan-php/deoplete-padawan'
on_event = 'InsertEnter'
on_ft = ['php']
depends = ['deoplete.nvim']
hook_source = '''
  augroup padawan-setting
    autocmd! FileType php setlocal completeopt-=preview
  augroup END
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = ['go']
depends = ['deoplete.nvim']
hook_source = '''
set completeopt+=noinsert
set completeopt+=noselect

let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
'''

[[plugins]]
repo        = 'autozimu/LanguageClient-neovim'
on_source   = ['deoplete.nvim']
rev         = 'next'
build = 'bash install.sh'
hook_source = '''
source ~/.config/nvim/plugins/LanguageClient-neovim.rc.vim
'''
# hook_post_update = '''
# !./install.sh
# !npm install -g vue-language-server
# '''
#--------------------
# /deoplete
#--------------------

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = ['FocusLost', 'CursorHold']
hook_add = '''
let g:gitgutter_diff_args='-w --indent-heuristic'
let g:gitgutter_highlight_lines = 0
let g:gitgutter_sign_added='✚'
let g:gitgutter_sign_modified='➜'
let g:gitgutter_sign_removed='✗'
let g:gitgutter_sign_removed_first_line='↑'
let g:gitgutter_sign_modified_removed='•'
let g:gitgutter_terminal_reports_focus=0
'''
hook_post_source = '''
"{{{
  if &background ==# 'light'
    hi GitGutterAddLine ctermbg=192 guibg=#f0f9e2
    hi GitGutterChangeLine ctermbg=230 guibg=#fff4c9
    hi GitGutterDeleteLine ctermbg=224 guibg=#ffe9ef
  elseif g:colors_name !=# 'nord'
    hi GitGutterAddLine ctermbg=233 guibg=#122b0c
    hi GitGutterChangeLine ctermbg=236 guibg=#342e0e
    hi GitGutterDeleteLine ctermbg=235 guibg=#4e2728
  endif
"}}}
'''

# html/css completion
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'xhtml', 'php']

# javascript completion
[[plugins]]
repo = 'ternjs/tern_for_vim'
on_ft = ['javascript']
hook_post_update = '''
!npm install -g tern
'''
hook_source = '''
let g:deoplete#sources#ternjs#types = 1
let g:deoplete#sources#ternjs#depths = 1
let g:deoplete#sources#ternjs#docs = 1
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = ['vue', 'toml']
hook_source = '''
  let g:precious_enable_switch_CursorMoved_i = {'*': 0}
  let g:precious_enable_switch_CursorHold    = {'*': 0}
	let g:precious_enable_switchers = {
    \	'*':    {'setfiletype': 0},
    \	'toml': {'setfiletype': 1},
    \	'html': {'setfiletype': 1},
    \	'vue':  {'setfiletype': 1},
	\ }
'''

# rust configuration
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
  let g:rustfmt_autosave = 1
  let g:rustfmt_command='~/.cargo/bin/rustfmt'
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rust']
hook_source = '''
  set hidden
  let g:racer_cmd='~/.cargo/bin/racer'
  let $RUST_SRC_PATH="/Users/sakochikodai/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src"
  let g:racer_experimental_completer = 1
  nmap <SPACE>gd <Plug>(rust-def)
  nmap <SPACE>gs <Plug>(rust-def-split)
  nmap <SPACE>gx <Plug>(rust-def-vertical)
  nmap <SPACE>K <Plug>(rust-doc)
'''

# python completion

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_i = 1
on_ft = ['python']
hook_source = '''
let g:jedi#force_py_version = 3
let g:jedi#use_splits_not_buffers = 'winwidth'
nnoremap <silent> <SPACE>pg :call jedi#goto()<cr>
nnoremap <silent> <SPACE>pag :call jedi#goto_assignments()<cr>
nnoremap <silent> <SPACE>pd :call jedi#show_documentation()<cr>
nnoremap <silent> <SPACE>prn :call jedi#rename()<cr>
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_i = 1
on_ft = ['python']

# go configuration
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'jodosha/vim-godebug'
on_ft = ['go']

#tweet vim setting
[[plugins]]
repo = 'basyura/TweetVim'
hook_source = '''
  let g:tweetvim_display_icon = 1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'mattn/favstar-vim'
